---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault

resources:
  - deploy.yml
  - sm.yml
  - rbac.yml
  - ns.yml
  - pm.yml

secretGenerator:
  - files:
      - config/config.hcl
    name: vault

images:
  - name: vault
    newName: vault
    newTag: 1.7.2
